Übersetzung hinzugefügt
flarum-lang/german pull request #34
Opened 2021-06-20 18:03 UTC by Justman10000

2021-06-21 17:17 UTC, Kakifrucht requested changes

2021-06-21 17:17 UTC, Kakifrucht commented on locale/justoverclock-flarum-ext-welcomebox
> +  forum:
First line same as with other file, must contain "flarum-ext-welcomebox" and filename must also match that as "flarum-ext-welcomebox.yml".

2021-06-21 17:17 UTC, Kakifrucht commented on locale/justoverclock-flarum-ext-welcomebox
> +    notregistered: Du bist aktuell nicht im Forum registriert.
5 translations are missing here.

2021-06-24 12:53 UTC, Justman10000 commented on locale/justoverclock-flarum-ext-welcomebox
> +    notregistered: Du bist aktuell nicht im Forum registriert.
Where?

2021-06-24 23:09 UTC, Kakifrucht commented on locale/justoverclock-flarum-ext-welcomebox
> +    notregistered: Du bist aktuell nicht im Forum registriert.
These ones: https://github.com/justoverclockl/flarum-ext-welcomebox/blob/main/resources/locale/en.yml#L8

2021-06-24 23:10 UTC, Kakifrucht commented on locale/justoverclock-flarum-ext-welcomebox
> +  justoverclock-flarum-ext-welcomebox:
First line is the same as in the original file, so only flarum-ext-welcomebox, filename would be flarum-ext-welcomebox.yml, and we still need the forum parent key.

2021-06-28 02:15 UTC, merged